const constant = {
  ENGLISH_LOCALE: "en",
  SPANISH_LOCALE: "el",
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  HTTP_STATUS_OK: 200,
  HTTP_STATUS_CREATED: 201,
  HTTP_STATUS_INTERNAL_ERROR: 500,
  HTTP_STATUS_BAD_REQUEST: 400,
  HTTP_STATUS_UNAUTHORIZED: 401,
  SALT_ROUNDS: 10,
  CANCEL_BOOKING_TIME_DIFFERENCE: 1,
};

export default constant;
